pipeline {
    agent any

    environment {
        CI = 'true'
        DOCKER_IMAGE = 'nihilag/week12-project:latest'   // Fixed username
        DOCKERHUB_USER = 'nihilag'                       // Your Docker Hub username
        DOCKERHUB_TOKEN = credentials('dockerhub-token') // Token stored in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Installing npm dependencies...'
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'Running unit tests...'
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo 'Running SonarQube analysis...'
                withSonarQubeEnv('sonarqube') {
                    sh """
                    /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonarscanner/bin/sonar-scanner \
                    -Dsonar.projectKey=week12-project \
                    -Dsonar.sources=./src
                    """
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                echo "Building Docker image..."
                sh "docker build -t ${DOCKER_IMAGE} -f docker/Dockerfile ."

                echo "Logging into Docker Hub..."
                sh "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin"

                echo "Pushing Docker image..."
                sh "docker push ${DOCKER_IMAGE}"
            }
        }

        stage('Deliver') {
            steps {
                echo 'Delivering application...'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
            sh 'docker logout || true'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
